### ISSUE TITLE
Role-based user workflows

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/farmers#123] opened 2023-02-10 10:44 UTC
Finalisation of straight-forward user workflows based on the user role – such that such that power users can be notified of changes proposed to all data held on the system and then approve / comment / reject these changes, based upon an agreed rule and procedure set.

**Comment by ygoex** [comment] 2023-02-13 11:00
Related issues:

- [ ] https://github.com/National-Forestry-Authority/farmers/issues/105

**Comment by ygoex** [comment] 2023-04-13 08:55
@Rashids2021 will provide a user workflow.

**Comment by peacog** [comment] 2023-05-30 14:29
Closed as duplicate of https://github.com/National-Forestry-Authority/farmers/issues/165

**Closed by peacog** 2023-05-30 14:29 UTC
Labels: Area/User management, Priority/Medium
